### ISSUE TITLE
is this still working ??

### ISSUE THREAD

**Issue by Xarcaneali** [localuser-isback/OperaGX-Free-Nitro-Generator#3]

**Comment by localuser-isback** [comment]
Dont think so, i belive the promotion is over.

**Comment by sprmcell** [comment]
"This 1-month Discord Nitro offer is available to Opera GX users. Redeem by 11:59 pm ET on July 16, 2024"  but when i run it i get, 

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.discord.gx.games/v1/direct-fulfillment. (Reason: CORS request did not succeed). Status code: (null).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.discord.gx.games/v1/direct-fulfillment. (Reason: CORS request did not succeed). Status code: (null).

Error: TypeError: NetworkError when attempting to fetch resource. [debugger eval code:38:21](chrome://devtools/content/webconsole/debugger%20eval%20code)
Error generating promo code links: TypeError: NetworkError when attempting to fetch resource.
```

was fun while it lasted unless im doing something wrong xd

**Comment by localuser-isback** [comment]
The codes are still valid i belive but i think they disabled the api to generate more.

**Comment by Xarcaneali** [comment]
Is there any solution or method that we could redeem them?

**Comment by localuser-isback** [comment]
Unless you already generated the codes then not really, i can provide some codes as i generated over 100k but you cant generate anymore. This is the only current alternative but i belive it requries an alienware account. https://support.discord.com/hc/en-us/articles/21412497781399-1-Month-Discord-Nitro-for-Alienware-Arena-Members-2024-Promo-FAQ

> Is there any solution or method that we could redeem them?

**Comment by localuser-isback** [comment]
This project also exists:

https://github.com/Pixens/Alienware-Promo-Generator

but requires a cap solver API key (which is paided) mabye ill make an alternative that does not require that.

**Comment by Xarcaneali** [comment]
@localuser-isback I've been diligently searching for Nitro codes since March 1st, but it's been 19 days without any success. If you could kindly provide me with some codes, it would be an immense favor. I would be incredibly grateful if you could send some to my email address at carlnesmith59@gmail.com. Thank you very much in advance

And it would be truly amazing if you could develop a similar bot to generate the codes for free. count me among those eagerly awaiting its development.

**Comment by Xarcaneali** [comment]
@localuser-isback 

Could you please let me know if you're able to assist with the Nitro codes or if there's anything else I can provide to facilitate the process? Your response would be greatly appreciated. Thank you.

**Comment by Xarcaneali** [comment]
@localuser-isback 

Could you please let me know if you're able to assist with the Nitro codes or if there's anything else I can provide to facilitate the process? I would greatly appreciate your response. Thank you.

**Comment by localuser-isback** [comment]
> @localuser-isback
> 
> Could you please let me know if you're able to assist with the Nitro codes or if there's anything else I can provide to facilitate the process? I would greatly appreciate your response. Thank you.

heres a bit over 500 codes:

https://pst.innomi.net/paste/ts3zzf99k5gtjoa2kpagnndt2wkhng33/authenticate

password is your github username.

**Comment by Xarcaneali** [comment]
every time i try it says 502 Bad Gateway

**Comment by Xarcaneali** [comment]
@localuser-isback 

It seems I'm encountering a 502 Bad Gateway error every time I attempt to use the link you provided with 'Xarcaneali' as the password.

**Comment by Xarcaneali** [comment]
@localuser-isback 
![Screenshot (530)](https://github.com/localuser-isback/OperaGX-Free-Nitro-Generator/assets/161977309/6034f110-b4df-4d22-9c06-d656dd64317b)

Every time i try the password I am either hit with 502 Bad Gateway or this

**Comment by Xarcaneali** [comment]
@localuser-isback 

the issue still persists
![Uploading Screenshot (531).png…]()
 man i am about to cry

**Comment by Xarcaneali** [comment]
![Screenshot (531)](https://github.com/localuser-isback/OperaGX-Free-Nitro-Generator/assets/161977309/ed971772-73d3-4c7b-b35b-bc70af5badad)


@localuser-isback the issue still persists man i am about to cry

**Comment by localuser-isback** [comment]
> ![Screenshot (531)](https://private-user-images.githubusercontent.com/161977309/316273046-ed971772-73d3-4c7b-b35b-bc70af5badad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyNDE3OTEsIm5iZiI6MTcxMTI0MTQ5MSwicGF0aCI6Ii8xNjE5NzczMDkvMzE2MjczMDQ2LWVkOTcxNzcyLTczZDMtNGM3Yi1iMzViLWJjNzBhZjViYWRhZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNFQwMDUxMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYzQ1ZjQ1ZDlkZjk1MzYyNmIzODhlNjJiOTM2MDM5YzQxZDliZTk4OTlmMDFkNjczMzY2MjVjMmNjOTNlNTU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CiilbD1NqjS5eeiPU99dOs46UrdNx148h0I-GsJMQ1M)
> 
> @localuser-isback the issue still persists man i am about to cry

Heres a reupload, https://pastebin.com/p6MzL6C0

password is your username, 1 day expiration so save it to file.

**Comment by Xarcaneali** [comment]
@localuser-isback 

![Screenshot (532)](https://github.com/localuser-isback/OperaGX-Free-Nitro-Generator/assets/161977309/46752f15-7824-499d-ad31-26524c2051e5)


Thank you so much for your assistance and for taking the trouble to re-upload the content. However, despite trying numerous codes, I'm consistently encountering the error message 'Uh oh, something went wrong.' I've attempted to redeem the codes on my 8-year-old account, my 1-month-old account, and even a new account, none of which have claimed Discord Nitro before. I'm truly sorry for putting you through so much trouble. Is there something I might be missing or any other steps I should take? Your help in resolving this matter would be greatly appreciated. Thank you once again for your support

**Comment by localuser-isback** [comment]
Hm tbh im not sure, i dont get that error. Try this code and lmk, mabye disable any extensions that could be messing with the browser, re-login to discord on browser, clear cache otherwise im not sure. Try this code aswell as some of the other possible solutions https://discord.com/billing/partner-promotions/1180231712274387115/eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..rMx9JM46v8g8pZGr.BbCWrq4OOisADejFN-WHL0YjM4wXYafW2t68QIswwdoyEp1GpCF0h6HLAObCoB-w9hSCF-S1bCAg9yckn0SxYl_dS25QZVHSETJMoi58LDE2yAWzIKBMPJlql_bCWjZjNIHufjE0nrrm38QL4VXv3GBAYuGNrmJao11y613DbX0NazVFJnO0YHAxlOfrGv5xXOc7IEWRwQZgzQ4Bv7irjEE1yBRJd5DGi4guoapBwFLxNsOvRvIy8aoq2cZpwcct0g6U7qC0.vIpZa2OCGm-D8EziiqSxCA

if nothing works then the codes might be expired and id recommend trying to do this:
https://support.discord.com/hc/en-us/articles/21412497781399-1-Month-Discord-Nitro-for-Alienware-Arena-Members-2024-Promo-FAQ
